<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Book_CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('book__categories')->insert([
            [
                "bc_id"=>"BC001",
                "book_id"=>"B001",
                "category_id"=>"C004"
            ],
            [
                "bc_id"=>"BC002",
                "book_id"=>"B002",
                "category_id"=>"C003"
            ],
            [
                "bc_id"=>"BC003",
                "book_id"=>"B003",
                "category_id"=>"C005"
            ],
            [
                "bc_id"=>"BC004",
                "book_id"=>"B004",
                "category_id"=>"C001"
            ],
            [
                "bc_id"=>"BC005",
                "book_id"=>"B005",
                "category_id"=>"C002"
            ],
            [
                "bc_id"=>"BC006",
                "book_id"=>"B006",
                "category_id"=>"C001"
            ],
            [
                "bc_id"=>"BC007",
                "book_id"=>"B007",
                "category_id"=>"C002"
            ],
            [
                "bc_id"=>"BC008",
                "book_id"=>"B008",
                "category_id"=>"C003"
            ],
            [
                "bc_id"=>"BC009",
                "book_id"=>"B009",
                "category_id"=>"C004"
            ],
            [
                "bc_id"=>"BC010",
                "book_id"=>"B010",
                "category_id"=>"C005"
            ],
            [
                "bc_id"=>"BC011",
                "book_id"=>"B011",
                "category_id"=>"C001"
            ],
            [
                "bc_id"=>"BC012",
                "book_id"=>"B012",
                "category_id"=>"C003"
            ],
            [
                "bc_id"=>"BC013",
                "book_id"=>"B013",
                "category_id"=>"C001"
            ],
            [
                "bc_id"=>"BC014",
                "book_id"=>"B014",
                "category_id"=>"C002"
            ],
            [
                "bc_id"=>"BC015",
                "book_id"=>"B015",
                "category_id"=>"C004"
            ],
            [
                "bc_id"=>"BC016",
                "book_id"=>"B016",
                "category_id"=>"C005"
            ],
            [
                "bc_id"=>"BC017",
                "book_id"=>"B017",
                "category_id"=>"C002"
            ],
            [
                "bc_id"=>"BC018",
                "book_id"=>"B018",
                "category_id"=>"C001"
            ],
            [
                "bc_id"=>"BC019",
                "book_id"=>"B019",
                "category_id"=>"C003"
            ],
            [
                "bc_id"=>"BC020",
                "book_id"=>"B020",
                "category_id"=>"C003"
            ],
            [
                "bc_id"=>"BC021",
                "book_id"=>"B021",
                "category_id"=>"C005"
            ],
            [
                "bc_id"=>"BC022",
                "book_id"=>"B019",
                "category_id"=>"C004"
            ],
            [
                "bc_id"=>"BC023",
                "book_id"=>"B020",
                "category_id"=>"C005"
            ]
        ]);
    }
}
